/*
 * shapelogic-cpp.cxx
 *
 *  Created on: Sep 17, 2008
 *      Author: Sami Badawi
 */

// generated by Fast Light User Interface Designer (fluid) version 1.0107

#ifndef shapelogic_cpp_h
#define shapelogic_cpp_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Menu_Bar.H>
#include <FL/Fl_Group.H>
#include <string>

class ShapeLogicFltk {
public:
  ShapeLogicFltk();
  Fl_Double_Window *_window;
  static Fl_Menu_Item menu_[];
private:
  void cb_Open_i(Fl_Menu_*, void*);
  static void cb_Open(Fl_Menu_*, void*);
  void cb_Undo_i(Fl_Menu_*, void*);
  static void cb_Undo(Fl_Menu_*, void*);
public:
  Fl_Group *_imageGroup;
private:
  Fl_Image * _currentImage;
  Fl_Image * _lastImage;
  std::string _filename;
};
#endif
