/*
 * shapelogic-cpp.cxx
 *
 *  Created on: Sep 17, 2008
 *      Author: Sami Badawi
 */

// generated by Fast Light User Interface Designer (fluid) version 1.0107

#include "shapelogic-cpp.h"
#include <iostream>
#include <FL/Fl_File_Chooser.H>

void ShapeLogicFltk::cb_Open_i(Fl_Menu_*, void*) {
  Fl_File_Chooser chooser(".",			// directory
		    "*",			// filter
		    Fl_File_Chooser::MULTI, 	// chooser type
		    "Title Of Chooser");	// title
  chooser.show();

// Block until user picks something.
//     (The other way to do this is to use a callback())
//
  while(chooser.shown())
  { Fl::wait(); }

// User hit cancel?
  if ( chooser.value() == NULL ) { 
    std::cout << "(User hit 'Cancel')\n"; 
    return; 
  }

// Print what the user picked
  std::cout << "--------------------\n";
  std::cout << "DIRECTORY: " << chooser.directory() << std::endl;
  std::cout << "FILE: " << chooser.value() << std::endl;
}
void ShapeLogicFltk::cb_Open(Fl_Menu_* o, void* v) {
  ((ShapeLogicFltk*)(o->parent()->user_data()))->cb_Open_i(o,v);
}

Fl_Menu_Item ShapeLogicFltk::menu_[] = {
 {"File", 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 14, 0},
 {"Open...", 0x4006f,  (Fl_Callback*)ShapeLogicFltk::cb_Open, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Save", 0x40073,  0, 0, 128, FL_NORMAL_LABEL, 0, 14, 0},
 {"Quit", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {"Edit", 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 14, 0},
 {"Undo", 0x4007a,  0, 0, 128, FL_NORMAL_LABEL, 0, 14, 0},
 {"Clear", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Fill", 0,  0, 0, 128, FL_NORMAL_LABEL, 0, 14, 0},
 {"Invert", 0x50069,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {"Image", 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 14, 0},
 {"Type", 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 14, 0},
 {"8-bit", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"16-bit", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"RGB Color", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {0,0,0,0,0,0,0,0,0},
 {"Process", 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 14, 0},
 {"Smooth", 0x50073,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Sharpen", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {"Plugins", 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 14, 0},
 {"ShapeLogic", 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {"ShapeLogicOld", 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {0,0,0,0,0,0,0,0,0},
 {"Help", 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 14, 0},
 {"About ShapeLogic", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {0,0,0,0,0,0,0,0,0}
};

ShapeLogicFltk::ShapeLogicFltk() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(690, 500, "ShapeLogic fltk v 0.1");
    w = o;
    o->user_data((void*)(this));
    { Fl_Menu_Bar* o = new Fl_Menu_Bar(0, 0, 690, 20);
      o->menu(menu_);
    }
    o->end();
    o->resizable(o);
  }
  w->show();
}

int main(int argc, char **argv) {
  ShapeLogicFltk shapeLogicFltk;
  return Fl::run();
}
