/*
 * shapelogic-cpp.cxx
 *
 *  Created on: Sep 17, 2008
 *      Author: Sami Badawi
 */

// generated by Fast Light User Interface Designer (fluid) version 1.0107

#include "shapelogic-cpp.h"

Fl_Menu_Item ShapeLogicFltk::menu_[] = {
 {"File", 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 14, 0},
 {"Open...", 0x4006f,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Save", 0x40073,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Quit", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {"Edit", 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 14, 0},
 {"Undo", 0x4007a,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Clear", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Fill", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Invert", 0x50069,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {"Image", 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 14, 0},
 {"Type", 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 14, 0},
 {"8-bit", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"16-bit", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"RGB Color", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {0,0,0,0,0,0,0,0,0},
 {"Process", 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 14, 0},
 {"Smooth", 0x50073,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Sharpen", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {"Plugins", 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 14, 0},
 {"ShapeLogic", 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {"ShapeLogicOld", 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {0,0,0,0,0,0,0,0,0},
 {"Help", 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 14, 0},
 {"About ShapeLogic", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {0,0,0,0,0,0,0,0,0}
};

ShapeLogicFltk::ShapeLogicFltk() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(690, 500, "ShapeLogic fltk v 0.1");
    w = o;
    o->user_data((void*)(this));
    { Fl_Menu_Bar* o = new Fl_Menu_Bar(0, 0, 690, 20);
      o->menu(menu_);
    }
    o->end();
    o->resizable(o);
    w->show();
  }
}

int main(int argc, char **argv) {
  ShapeLogicFltk shapeLogicFltk;
  return Fl::run();
}
