/*
 * shapelogic-cpp.cxx
 *
 *  Created on: Sep 17, 2008
 *      Author: Sami Badawi
 */

// generated by Fast Light User Interface Designer (fluid) version 1.0107

#ifndef shapelogic_cpp_h
#define shapelogic_cpp_h
int main_proxy(int argc, char **argv);
#endif
